// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AR30Web.Data
{
    [Table("tbIssuer")]
    public partial class Issuer
    {
        [Key]
        [Column("cId")]
        public int Id { get; set; }
        [Required]
        [Column("cName")]
        [StringLength(50)]
        [Display(Name="Name")]
        public string Name { get; set; }
        [Column("cMailerType")]
        [Display(Name = "Type")]
        public byte MailerType { get; set; }
        [Column("cPhone1")]
        [Display(Name = "Phone 1")]
        public int Phone1 { get; set; }
        [Column("cPhone2")]
        [Display(Name = "Phone 2")]
        public int Phone2 { get; set; }
        [Column("cPhone3")]
        [Display(Name = "Phone 3")]
        public int Phone3 { get; set; }
    }
}