// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AR30Web.Data
{
[Table("tbPhoneNumber")]
    public partial class PhoneNumber
    {
        [Key]
        [Column("cId")]
        public int CId { get; set; }
        [Column("cPrefix")]
        public short CPrefix { get; set; }
        [Column("cNumber")]
        public int CNumber { get; set; }
    }
}