// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AR30Web.Data
{
[Table("tbPrefix")]
    public partial class Prefix
    {
        [Key]
        [Column("cId")]
        public short CId { get; set; }
        [Required]
        [Column("cPrefixL")]
        [StringLength(10)]
        public string CPrefixL { get; set; }
        [Required]
        [Column("cPrefixS")]
        [StringLength(10)]
        public string CPrefixS { get; set; }
    }
}