// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AR30Web.Data
{
[Table("tbSession")]
    public partial class Session
    {
        [Key]
        [Column("cId")]
        public int CId { get; set; }
        [Column("cDT", TypeName = "datetime")]
        public DateTime CDt { get; set; }
        [Column("cB")]
        public int? CB { get; set; }
        [Column("cE")]
        public int? CE { get; set; }
    }
}